Correlación no implica causalidad. 

In [1]:
import pandas as  pd
import numpy as np
df=pd.read_csv("C:/Users/jenny/Documents/GITHUB/Linkedin_courses_bbdd/base_datos_2008.csv", nrows=100000)

In [2]:
np.corrcoef(df["ArrDelay"], df["DepDelay"])

array([[nan, nan],
       [nan, nan]])

Da vacío porque el las columnas involucradas tienen valores faltantes y eso afecta el resultado

In [3]:
df.dropna(inplace=True, subset=["ArrDelay","DepDelay"])

In [4]:
#ahora si da una matriz
np.corrcoef(df["ArrDelay"], df["DepDelay"])

array([[1.       , 0.9422735],
       [0.9422735, 1.       ]])

In [5]:
#Podemos calcular la matriz de correlación de mas de dos variables
np.corrcoef([df["ArrDelay"], df["DepDelay"],df["DepTime"]])

array([[1.        , 0.9422735 , 0.23241529],
       [0.9422735 , 1.        , 0.25725889],
       [0.23241529, 0.25725889, 1.        ]])

In [6]:
df.dropna(inplace=True, subset=["Year", "Cancelled","Diverted"])

In [7]:
df.corr() #Matriz de correlaciones de todo el dataset

Year  Month  DayofMonth  DayOfWeek   DepTime  CRSDepTime  \
Year                NaN    NaN         NaN        NaN       NaN         NaN   
Month               NaN    NaN         NaN        NaN       NaN         NaN   
DayofMonth          NaN    NaN    1.000000  -0.118851 -0.001168    0.003749   
DayOfWeek           NaN    NaN   -0.118851   1.000000  0.031111    0.024400   
DepTime             NaN    NaN   -0.001168   0.031111  1.000000    0.985504   
CRSDepTime          NaN    NaN    0.003749   0.024400  0.985504    1.000000   
ArrTime             NaN    NaN   -0.004445   0.021947  0.796903    0.795609   
CRSArrTime          NaN    NaN   -0.001941   0.027785  0.852191    0.862782   
FlightNum           NaN    NaN    0.072588  -0.039560  0.023409    0.023789   
ActualElapsedTime   NaN    NaN    0.004568   0.015945 -0.069542   -0.074644   
CRSElapsedTime      NaN    NaN   -0.006886   0.017744 -0.065937   -0.070060   
AirTime             NaN    NaN    0.000893   0.014324 -0.065054   -0.069232   
ArrDelay            NaN    NaN    0.027501   0.085299  0.232415    0.180684   
DepDelay            NaN    NaN    0.007231   0.098220  0.257259    0.202200   
Distance            NaN    NaN   -0.006686   0.017525 -0.056849   -0.061167   
TaxiIn              NaN    NaN   -0.012618   0.034878  0.029098    0.024048   
TaxiOut             NaN    NaN    0.040429   0.000337 -0.068401   -0.075218   
Cancelled           NaN    NaN         NaN        NaN       NaN         NaN   
Diverted            NaN    NaN         NaN        NaN       NaN         NaN   
CarrierDelay        NaN    NaN   -0.061650   0.031015  0.029925   -0.015536   
WeatherDelay        NaN    NaN    0.055178   0.008769 -0.018628   -0.057462   
NASDelay            NaN    NaN    0.111780   0.001660 -0.128269   -0.149643   
SecurityDelay       NaN    NaN   -0.012357   0.024726 -0.022763   -0.025722   
LateAircraftDelay   NaN    NaN    0.079725   0.079787  0.229938    0.227241   

                    ArrTime  CRSArrTime  FlightNum  ActualElapsedTime  ...  \
Year                    NaN         NaN        NaN                NaN  ...   
Month                   NaN         NaN        NaN                NaN  ...   
DayofMonth        -0.004445   -0.001941   0.072588           0.004568  ...   
DayOfWeek          0.021947    0.027785  -0.039560           0.015945  ...   
DepTime            0.796903    0.852191   0.023409          -0.069542  ...   
CRSDepTime         0.795609    0.862782   0.023789          -0.074644  ...   
ArrTime            1.000000    0.887002   0.011193           0.013706  ...   
CRSArrTime         0.887002    1.000000   0.014385           0.025615  ...   
FlightNum          0.011193    0.014385   1.000000           0.024159  ...   
ActualElapsedTime  0.013706    0.025615   0.024159           1.000000  ...   
CRSElapsedTime     0.016936    0.032250   0.025279           0.983501  ...   
AirTime            0.018445    0.030644   0.021619           0.992457  ...   
ArrDelay           0.076353    0.142571  -0.001017          -0.013101  ...   
DepDelay           0.091164    0.171454   0.002810           0.020641  ...   
Distance           0.024675    0.042641   0.017180           0.963610  ...   
TaxiIn             0.044000    0.042752   0.007277           0.183375  ...   
TaxiOut           -0.062210   -0.061937   0.023976           0.167747  ...   
Cancelled               NaN         NaN        NaN                NaN  ...   
Diverted                NaN         NaN        NaN                NaN  ...   
CarrierDelay      -0.027949   -0.004882  -0.020801           0.021032  ...   
WeatherDelay      -0.033068   -0.049083   0.004887           0.039746  ...   
NASDelay          -0.067516   -0.119460   0.002978           0.208190  ...   
SecurityDelay     -0.005993   -0.016722  -0.007659           0.014323  ...   
LateAircraftDelay -0.050018    0.171666  -0.002957          -0.076740  ...   

                   Distance    TaxiIn   TaxiOut  Cancelled  Diverted  \
Year                

In [8]:
df.drop(inplace=True, columns=["Month"])
corr=round(df.corr(),3)
corr=round(df.corr(),3)
corr.style.background_gradient()

C:\Users\jenny\.conda\envs\research\lib\site-packages\pandas\io\formats\style.py:2813: RuntimeWarning: All-NaN slice encountered
  smin = np.nanmin(gmap) if vmin is None else vmin
C:\Users\jenny\.conda\envs\research\lib\site-packages\pandas\io\formats\style.py:2814: RuntimeWarning: All-NaN slice encountered
  smax = np.nanmax(gmap) if vmax is None else vmax


# Test de la Chi-cuadrado

In [9]:
import pandas as pd
import numpy as np
df=pd.read_csv("C:/Users/jenny/Documents/GITHUB/Linkedin_courses_bbdd/base_datos_2008.csv")

In [10]:
np.random.seed(0) #fijamos la semilla para erplicar el resultado
df = df[df["Origin"].isin(["HOU","ATL","IND"])]
df = df.sample(frac=1)
df = df[0:10000]

In [11]:
df["BigDelay"] = df["ArrDelay"]>30
observados = pd.crosstab(index=df["BigDelay"],columns=df["Origin"], margins=True)

In [12]:
observados

Origin     ATL   HOU  IND    All
BigDelay                        
False     6927   883  765   8575
True      1197   129   99   1425
All       8124  1012  864  10000

In [13]:
from scipy.stats import chi2_contingency

In [14]:
test = chi2_contingency(observados)

In [15]:
test

(8.939538453043031,
 0.17700704816414425,
 6,
 array([[ 6966.33,   867.79,   740.88,  8575.  ],
        [ 1157.67,   144.21,   123.12,  1425.  ],
        [ 8124.  ,  1012.  ,   864.  , 10000.  ]]))

In [16]:
esperados = pd.DataFrame(test[3])

In [17]:
esperados

0        1       2        3
0  6966.33   867.79  740.88   8575.0
1  1157.67   144.21  123.12   1425.0
2  8124.00  1012.00  864.00  10000.0

In [18]:
#valores teóricos esperados
esperados_rel= round(esperados.apply(lambda r: r/len(df)*100, axis=1),2)

In [19]:
#valores teóricos observados
observados_rel= round(observados.apply(lambda r: r/len(df)*100, axis=1),2)

In [20]:
esperados_rel

0      1     2       3
0  69.66   8.68  7.41   85.75
1  11.58   1.44  1.23   14.25
2  81.24  10.12  8.64  100.00

In [21]:
observados_rel

Origin      ATL    HOU   IND     All
BigDelay                            
False     69.27   8.83  7.65   85.75
True      11.97   1.29  0.99   14.25
All       81.24  10.12  8.64  100.00

In [22]:
test[1]

0.17700704816414425

### Resumen te  test de Hipótesis

* Si el p-valor< 0.05 hay diferencias significativas: Hay relación entre las variables
* So el p-valor>0.05, no hay diferencia significativas: No hay relación entre las variables

# Análisis de Datos Extremos

In [23]:
import pandas as pd
import numpy as np
df=pd.read_csv("C:/Users/jenny/Documents/GITHUB/Linkedin_courses_bbdd/base_datos_2008.csv")

In [24]:
x=df["ArrDelay"].dropnaa()

AttributeError: 'Series' object has no attribute 'dropnaa'

In [ ]:
Q1 = np.percentile(x,25)
Q2 = np.percentile(x,50)
Q3 = np.percentile(x,75)
rangointer = Q3 - Q1

In [ ]:
# Un criterio básico para calcular outliers es calcular umbrales
umbralsuperior = Q3 + 1.5 * rangointer
umbralinferior = Q1 - 1.5 * rangointer


In [ ]:
umbralsuperior

In [ ]:

umbralinferior

In [ ]:
np.mean(x>umbralsuperior)

In [ ]:
np.mean(x<umbralinferior)

In [ ]:
from sklearn.covariance import EllipticEnvelope # pip install -U scikit-learn scipy matplotlib

In [ ]:
outliers=EllipticEnvelope(contamination=0.01)

In [ ]:
var_list=["DepDelay","TaxiIn", "TaxiOut", "CarrierDelay", "WeatherDelay","NASDelay","SecurityDelay" ]

In [ ]:
x=np.array(df.loc[:,var_list].dropna())

In [ ]:
outliers.fit(x)

In [ ]:
pred = outliers.predict(x)

In [ ]:
pred

In [ ]:
elips_outliers = np.where(pred == -1)[0]

In [ ]:
elips_outliers #indices donde estan los outliers

Con esta metodología podemos detectar aquellso puntos que están lejos a la distribución de la muestra

# Transformar un dataframe en una base de datos relacional

In [ ]:
import pandas as pd
data = [(1, "Joan", "Gasul",25,1,"Libreta", 1.2,.4,0.8,3, "03-02-2018"),
        (1, "Joan", "Gasul",25,2,"Bolígrafo", 0.4,.15,0.25,1, "03-02-2018"),
        (1, "Joan", "Gasul",25,1,"Libreta", 1.2,.4,0.8,3, "25-02-2018"),
        (2, "Joan", "López",33,1,"Bolígrafo", 0.4,0.15,0.25,4, "01-02-2018"),
        (2, "Joan", "López",33,1,"Libreta", 1.2,0.4,0.8,10, "05-03-2018"),
        (3, "Maria", "García",40,1,"Libreta", 1.2,0.4,0.8,20, "13-04-2018"),
        (3, "Maria", "García",40,2,"Bolígrafo", 0.4,0.15,0.25,1, "19-02-2018"),
        (3, "Maria", "García",40,2,"Bolígrafo", 0.4,0.15,0.25,1, "03-02-2018")]

labels=["Comprador_id","Nombre","Apellido","Edad", "Producto_id","Producto","Precio","Coste","Margen", "Cantidad","Fecha"]

In [ ]:
 #convertir en dataframe
df = pd.DataFrame.from_records(data, columns = labels)

In [ ]:
df

In [ ]:
#Vamos a crear una base de datos para cada comprador
compradores = df.drop_duplicates(subset  = "Comprador_id", keep = "first")

In [ ]:
compradores

In [ ]:
compradores = compradores[["Comprador_id", "Nombre","Apellido", "Edad"]]

In [ ]:
productos = df.drop_duplicates(subset  = "Producto_id", keep = "first")

In [ ]:
productos = productos[["Producto_id", "Producto", "Precio","Coste", "Margen"]]
productos

In [ ]:
compras = df[["Comprador_id", "Producto_id", "Fecha", "Cantidad"]]
compras

# Joins. Trabajar con base de datos relacionales

In [ ]:
import pandas as pd
consumidores = [("A", "Móvil"),("B", "Móvil"),("A","Portátil"),("A","Tablet"),("B","Tablet"),("C","Portátil"),("D", "Smartwatch"),("E","Consola")]
con_labels = ["Consumidor", "Producto"]
con_df = pd.DataFrame.from_records(consumidores,columns=con_labels)
productores=[("a", "Móvil"), ("a","Smartwatch"),("a", "Tablet"), ("b", "Portátil"),("c","Sobremesa"), ("c","Portátil")]
prod_labels=["Productor","Producto"]
prod_df = pd.DataFrame.from_records(productores, columns = prod_labels)

In [ ]:
con_df

In [ ]:
prod_df

In [ ]:
pd.merge(con_df, prod_df, on="Producto", how="outer") #outer son comunes y no comunes, los no comunes se completan con NaN

In [ ]:
pd.merge(con_df, prod_df, on="Producto", how="inner") #inner son solo los comunes

In [ ]:
pd.merge(con_df, prod_df, on="Producto", how="left") #left son solo los de la izquierda

In [ ]:
pd.merge(con_df, prod_df, on="Producto", how="right") #right son solo los de la izquierda

# Paralelizar

In [ ]:
import pandas as pd
import numpy as np
from joblib import Parallel, delayed

df=pd.read_csv("C:/Users/jenny/Documents/GITHUB/Linkedin_courses_bbdd/base_datos_2008.csv", nrows=100000)

In [ ]:
df_sub = df[["CarrierDelay","WeatherDelay","NASDelay","SecurityDelay","LateAircraftDelay"]]
df_sub.head(10)

In [ ]:
def retraso_maximo(fila):
    if not np.isnan(fila).any():
        names=["CarrierDelay","WeatherDelay","NASDelay","SecurityDelay","LateAircraftDelay"]
        return names[fila.index(max(fila))]
    else:
        return "None"

In [ ]:
results = []
for fila in df_sub.values.tolist():
    results.append(retraso_maximo(fila))

In [ ]:
results

In [ ]:
result = Parallel(n_jobs=2, backend="multiprocessing")(
            map(delayed(retraso_maximo), df_sub.values.tolist()))

In [ ]:
result